---
- hosts: localhost
  user: '{{ username }}'
  connection: local

  vars_files:
    - vars/main.yml
    - vars/local.yml

  vars_prompt:
    - name: password
      prompt: What is your App Store password?

  roles:
    - geerlingguy.mac.homebrew	
    - geerlingguy.mac.mas
    - geerlingguy.mac.dock

  tasks:
    - name: "Remove desktop files/items"
      command: "defaults write com.apple.finder CreateDesktop false"

    - name: "Restart finder"
      command: "killall Finder"

